### ISSUE TITLE
SessionKeyDecryptionError

### ISSUE THREAD

**Issue by n1ghtfox** [TarlogicSecurity/kerbrute#2]
Traceback (most recent call last):
  File "kerbrute.py", line 31, in <module>
    from impacket.krb5.kerberosv5 import getKerberosTGT, KerberosError, SessionKeyDecryptionError
ImportError: cannot import name SessionKeyDecryptionError

**Comment by zer1t0** [comment]
I'm unable to reproduce the issue. Could it be due to an outdated version of Impacket?

**Comment by aguilbau** [comment]
I can reproduce when running kerbrute with python2,
this is because the shebang is
`#!/usr/bin/env python`

**Comment by ghost** [comment]
Is there a way to fix this?

**Comment by zer1t0** [comment]
I can't reproduce neither with python3 nor python2. Could you provide me more information, such as the exactly version of python and impacket?

In my tests I used python 3.7.3 and python 2.7.16, both with impacket version v0.9.21

**Comment by ghost** [comment]
I know it was version 3.6.6 and 2.7.15 of Python not sure about version of impacket.  But, I think the issue was on my side.  I'm running a Kali VM for OSCP and just found out I'm using an outdated version.  They have two different versions available for download.  I was having problems with other packages as well and chatted with support last night.  Haven't spun up the new version yet, but I'll try it again later today when I do.
